### ISSUE TITLE
MduleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by infinotiver** [yashppawar/classroom-mask-detector#1]
I got this error while using it 
```py
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-36b14e86fbce> in <module>
      1 import numpy as np
----> 2 import cv2
      3 import face_recognition
      4 
      5 from keras.models import load_model

ModuleNotFoundError: No module named 'cv2'

```

**Comment by yashppawar** [comment]
Hey !
please make sure that you have installed all the modules necessary `conda env create -f requirements.yml` should install all of them, but if it did not, do `pip install opencv-python` to install cv2 

(**Note**: project is built in python 3, so use pip3 if needed)

**Comment by infinotiver** [comment]
Ok thanks but I couldnt understand this 
`conda env create -f requirements.yml` . I have to write it ? where I am using jupyter notebook

**Comment by yashppawar** [comment]
> Ok thanks but I couldnt understand this `conda env create -f requirements.yml` . I have to write it ? where I am using jupyter notebook

the command is to be ran in a terminal, I would suggest to run it using anaconda cmd, or anaconda powershell (if on windows), or any terminal should work in linux & mac. 

or just add `!` in before the command (`!onda env create -f requirements.yml`) and run it in a jupyter notebook's cell (not recommended)

**Comment by yashppawar** [comment]
@prakarsh17 let me know when to close the issue
